---
name: Continuous integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'
  pull_request:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    strategy:
      fail-fast: false
      matrix:
        helm:
          - latest
          - 3.5.1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - uses: azure/setup-helm@v1
        with:
          version: ${{ matrix.helm }}
      - run: helm lint .

      - run: helm dependency update tests/chart
      - run: helm template --namespace=default test tests/chart > tests/actual.yaml
      - run: diff -Naur --ignore-trailing-space tests/expected.yaml tests/actual.yaml
        if: matrix.helm == 'latest'
      - run: helm lint tests/chart

      - name: Setup k3s/k3d
        run: c2cciutils-k8s-install
      - run: kubectl apply -f tests/expected.yaml

      - name: Publish
        run: c2cciutils-publish
        if: matrix.helm == 'latest'
